Repository prakharshreyash/CodeBank, pull requests merged in 2022-10, with the labels that each got.

#2 Code2
  Python Codes.ipynb
Labels: hacktoberfest, hacktoberfest2022

#4 Code4
  Pandas Codes.ipynb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 Code5
  Python Programs.ipynb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Ashish code1
  binary.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Ashish code2
  circular.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 Ashish code3
  insertion.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Ashish code4
  sorting.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Suman code#1
  Directed_graph.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Suman code#2
  Trie_implementation.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Suman code#3
  LCS.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Suman code#4
  Knapsack.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Kalim code#1
  Hash_with_chain.cpp
  Segement_tree.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#17 Reverse a linked list
  Reverse a linked list
  Reverse a linked list in c++
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Create fcfs scheduling in c++
  SJF Scheduling in c++
  fcfs scheduling in c++
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 Create SJF Scheduling code
  SJF Scheduling code
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 Create SRTF scheduling in c++
  SRTF scheduling in c++
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
